# trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Install Terraform
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.6.0'

# Terraform Init
- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: 'MyServiceConnection'
    backendAzureRmResourceGroupName: 'my-tfstate-rg'
    backendAzureRmStorageAccountName: 'mytfstateaccount'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

# Terraform Plan
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: 'MyServiceConnection'

# Terraform Apply
- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: 'MyServiceConnection'
    commandOptions: '-auto-approve'
